/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoiceAgentIndexRouteImport } from './routes/voice-agent/index'
import { Route as ChatbotIndexRouteImport } from './routes/chatbot/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceAgentIndexRoute = VoiceAgentIndexRouteImport.update({
  id: '/voice-agent/',
  path: '/voice-agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotIndexRoute = ChatbotIndexRouteImport.update({
  id: '/chatbot/',
  path: '/chatbot/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/chatbot': typeof ChatbotIndexRoute
  '/voice-agent': typeof VoiceAgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/chatbot': typeof ChatbotIndexRoute
  '/voice-agent': typeof VoiceAgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/chatbot/': typeof ChatbotIndexRoute
  '/voice-agent/': typeof VoiceAgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/tanstack-query' | '/chatbot' | '/voice-agent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/tanstack-query' | '/chatbot' | '/voice-agent'
  id: '__root__' | '/' | '/demo/tanstack-query' | '/chatbot/' | '/voice-agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ChatbotIndexRoute: typeof ChatbotIndexRoute
  VoiceAgentIndexRoute: typeof VoiceAgentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-agent/': {
      id: '/voice-agent/'
      path: '/voice-agent'
      fullPath: '/voice-agent'
      preLoaderRoute: typeof VoiceAgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot/': {
      id: '/chatbot/'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ChatbotIndexRoute: ChatbotIndexRoute,
  VoiceAgentIndexRoute: VoiceAgentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
